### ISSUE TITLE
Can't find crashes in exercise one.

### ISSUE THREAD

**Issue by lentikr** [epi052/fuzzing-101-solutions#3]
Hello.
I'm following your code to solve exercise one with LibAFL(version 0.8.1). I found in your blog that you used 10 mins to generate 600+ inputs. But my corpus grow slowly after the size comes to 140. And I can't find any timeout in hours. I don't know where the problem is. Can anyone help me?
OS: Ubuntu20.04 on VMware
[main(rs format).txt](https://github.com/epi052/fuzzing-101-solutions/files/9486264/main.rs.format.txt)
![image](https://user-images.githubusercontent.com/95539012/188349538-9880def8-a9fa-48bc-8272-b1a0ac85dda6.png)

**Comment by epi052** [comment]
hey there, sorry, i spaced on replying to this; did you ever get it solved?

**Comment by lentikr** [comment]
> hey there, sorry, i spaced on replying to this; did you ever get it solved?

Thanks, I solved the problem. Just del the shemem_provider function when building the fork_server. The function means the fuzzer get the input from memory, that's not what I want. For detailed information, we can check the document of libafl's API.

```rust
let fork_server = ForkserverExecutor::builder()
       .program("./xpdf/install/bin/pdftotext".to_string())
       .parse_afl_cmdline(&[String::from("@@")])
       .shmem_provider(&mut shmem_provider)// delete this line
       .build(tuple_list!(time_observer, edges_observer))
       .unwrap();
```
